import type { SuiteStrings } from "./en.js";

export const de: SuiteStrings = {
  actions: {
    save: "Speichern",
    cancel: "Abbrechen",
    reset: "Zurücksetzen",
    restoreDefaults: "Standard wiederherstellen",
    delete: "Löschen",
    create: "Anlegen",
    back: "Zurück",
    close: "Schließen",
  },
  status: {
    success: "Erfolg",
    warning: "Warnung",
    error: "Fehler",
    info: "Info",
    running: "Läuft",
    failed: "Fehlgeschlagen",
    recovered: "Wiederhergestellt",
  },
  filter: {
    all: "{{field}}: Alle",
    allValue: "Alle",
    placeholder: "Filtern…",
    reset: "Filter zurücksetzen",
    label: "Liste filtern",
    hint: 'Durchsucht alle Spalten; mehrere Wörter müssen alle passen. Eine Wortgruppe in "Anführungszeichen" bleibt zusammen. Einzelne Zeichen werden ignoriert.',
  },
  sort: {
    label: "Sortiert nach",
    hint: "Legt fest, in welcher Reihenfolge die Einträge erscheinen.",
    updated: "Zuletzt bearbeitet",
  },
  pagination: {
    firstPage: "Erste Seite",
    prevPage: "Vorherige Seite",
    nextPage: "Nächste Seite",
    lastPage: "Letzte Seite",
    summary: "Seite {{page}} / {{totalPages}} ({{total}})",
    pageSize: "{{size}} pro Seite",
    pageSizeLabel: "Zeilen pro Seite",
    pageSizeHint: "Wie viele Einträge eine Seite zeigt.",
    firstPageDisabled: "Erste Seite: möglich, sobald du auf einer späteren Seite bist.",
    prevPageDisabled: "Vorherige Seite: möglich, sobald du auf einer späteren Seite bist.",
    nextPageDisabled: "Nächste Seite: möglich, sobald es nach dieser Seite eine weitere gibt.",
    lastPageDisabled: "Letzte Seite: möglich, sobald es nach dieser Seite eine weitere gibt.",
  },
  list: {
    empty: "Noch keine Einträge.",
    noMatches: "Keine Einträge gefunden.",
  },
  nav: {
    label: "Hauptnavigation",
    toggleSidebar: "Seitenleiste ein-/ausklappen",
    home: "Öffnet das Dashboard.",
    backToDashboard: "Zurück zum Dashboard",
    helpHint: "Öffnet die Hilfe mit Anleitungen zu allen Bereichen.",
    shared: {
      help: "Hilfe",
      users: "Benutzer",
      permissions: "Berechtigungen",
      systemLog: "System-Log",
      backupRestore: "Backup & Restore",
      general: "Allgemein",
      ai: "KI",
      integrations: "Integrationen",
      backup: "Backup",
      system: "System",
      loginSecurity: "Login & Sicherheit",
      mediaLibrary: "Medien-Bibliothek",
      textBlocks: "Text-Bausteine",
      brandKits: "Brand kits",
    },
  },
  account: {
    menu: "Kontomenü",
    menuHint: "Öffnet das Menü mit Profil, Sprache, Darstellung und Abmelden.",
    profile: "Profil",
    profileHint: "Öffnet das eigene Profil.",
    language: "Sprache",
    languageHint:
      "Wechselt die Sprache der Oberfläche; die Wahl bleibt auf diesem Gerät gespeichert.",
    appearance: "Darstellung",
    system: "System",
    light: "Hell",
    dark: "Dunkel",
    appearanceHint: "Stellt die Darstellung auf „{{mode}}“.",
    changePassword: "Passwort ändern",
    changePasswordHint: "Öffnet das Formular, um das eigene Passwort zu ändern.",
    changePasswordLocked:
      "Letzter aktiver Administrator — Passwort gesperrt. Lege zuerst einen zweiten Administrator an.",
    security: "Sicherheit / MFA",
    securityHint: "Zweiten Faktor und Wiederherstellungscodes verwalten.",
    logOut: "Abmelden",
    logOutHint: "Meldet ab und kehrt zur Anmeldung zurück.",
    notAvailable: "Noch nicht verfügbar",
  },
  language: {
    en: "English",
    de: "Deutsch",
    es: "Español",
  },
  search: {
    label: "Suchen",
    placeholder: "Suchen …",
    title: "Suchen",
    subtitle: "Durchsucht {{areas}}.",
    empty: "Nichts gefunden in {{areas}}.",
    loading: "Wird gesucht …",
    failed: "Die Suche ist fehlgeschlagen. Versuche es erneut.",
    results: "Suchergebnisse",
    areaSeparator: ", ",
    fieldHint: "Öffnet die Suche über alle Bereiche; Tastenkürzel {{shortcut}}.",
    inputHint: "Findet Einträge aller Bereiche nach Titel oder Inhalt.",
    hitHint: "Öffnet diesen Treffer.",
  },
  version: {
    label: "Versionsinfo",
    hint: "Zeigt Version, Commit und Build dieser Instanz.",
    title: "Version",
    version: "Version",
    noRelease: "Kein Release (Stand ohne Tag)",
    commit: "Commit",
    buildDate: "Build-Datum",
  },
  confirmDelete: {
    title: "Löschen bestätigen",
    cancelHint: "Schließt den Dialog, ohne etwas zu löschen.",
    cancelDisabledHint: "Schließen geht wieder, sobald das Löschen abgeschlossen ist.",
    confirmHint: "Löscht endgültig; das lässt sich nicht rückgängig machen.",
  },
  settings: {
    saveHint: "Speichert die Änderungen auf dieser Seite.",
    saveDisabledHint: "Speichern geht, sobald du hier etwas geändert hast.",
    saveInvalidHint: "Speichern geht, sobald alle Angaben hier gültig sind.",
    resetHint: "Verwirft die ungespeicherten Änderungen auf dieser Seite.",
    resetDisabledHint: "Zurücksetzen geht, sobald du hier etwas geändert hast.",
  },
  timezone: {
    placeholder: "Zeitzone suchen…",
    empty: "Keine passende Zeitzone",
  },
};
