import type { SuiteStrings } from "./en.js";

export const de: SuiteStrings = {
  actions: {
    save: "Speichern",
    cancel: "Abbrechen",
    reset: "Zurücksetzen",
    restoreDefaults: "Standard wiederherstellen",
    edit: "Bearbeiten",
    delete: "Löschen",
    create: "Anlegen",
    upload: "Hochladen",
    back: "Zurück",
    close: "Schließen",
    replace: "Ersetzen",
    remove: "Entfernen",
    testConnection: "Verbindung testen",
    retry: "Erneut versuchen",
  },
  status: {
    success: "Erfolg",
    warning: "Warnung",
    error: "Fehler",
    info: "Info",
    running: "Läuft",
    done: "Fertig",
    failed: "Fehlgeschlagen",
    recovered: "Wiederhergestellt",
  },
  state: {
    succeeded: "Erfolgreich",
    ok: "OK",
    connected: "Verbunden",
    active: "Aktiv",
    failed: "Fehlgeschlagen",
    error: "Fehler",
    failing: "Gestört",
    untested: "Ungetestet",
    unconfigured: "Nicht konfiguriert",
    expiring: "Läuft ab",
    running: "Läuft",
    inProgress: "In Arbeit",
    set: "Gesetzt",
    notSet: "Nicht gesetzt",
    notTestable: "Nicht testbar",
    unknown: "Unbekannt",
  },
  filter: {
    all: "{{field}}: Alle",
    allValue: "Alle",
    placeholder: "Filtern…",
    searchPlaceholder: "Suchen ({{fields}}) …",
    reset: "Filter zurücksetzen",
    label: "Liste filtern",
    hint: 'Durchsucht alle Spalten; mehrere Wörter müssen alle passen. Eine Wortgruppe in "Anführungszeichen" bleibt zusammen. Einzelne Zeichen werden ignoriert.',
  },
  sort: {
    label: "Sortiert nach",
    hint: "Legt fest, in welcher Reihenfolge die Einträge erscheinen.",
    updated: "Zuletzt bearbeitet",
  },
  pagination: {
    firstPage: "Erste Seite",
    prevPage: "Vorherige Seite",
    nextPage: "Nächste Seite",
    lastPage: "Letzte Seite",
    summary: "Seite {{page}} / {{totalPages}} ({{total}})",
    pageSize: "{{size}} pro Seite",
    pageSizeLabel: "Zeilen pro Seite",
    pageSizeHint: "Wie viele Einträge eine Seite zeigt.",
    firstPageDisabled: "Erste Seite: möglich, sobald du auf einer späteren Seite bist.",
    prevPageDisabled: "Vorherige Seite: möglich, sobald du auf einer späteren Seite bist.",
    nextPageDisabled: "Nächste Seite: möglich, sobald es nach dieser Seite eine weitere gibt.",
    lastPageDisabled: "Letzte Seite: möglich, sobald es nach dieser Seite eine weitere gibt.",
  },
  list: {
    empty: "Noch keine Einträge.",
    noMatches: "Keine Treffer für diesen Filter.",
    emptyOf: "Noch keine {{objects}}.",
    actions: "Aktionen",
    emptyValue: "leer",
  },
  severity: {
    error: "Fehler",
    warning: "Warnung",
    info: "Info",
  },
  outcome: {
    succeeded: "Erfolgreich",
    failed: "Fehlgeschlagen",
    note: "Notiz",
  },
  columns: {
    type: "Typ",
  },
  view: {
    label: "Ansicht",
    table: "Tabelle",
    tiles: "Kacheln",
  },
  nav: {
    label: "Hauptnavigation",
    toggleSidebar: "Seitenleiste ein-/ausklappen",
    home: "Öffnet das Dashboard.",
    backToDashboard: "Zurück zum Dashboard",
    helpHint: "Öffnet die Hilfe mit Anleitungen zu allen Bereichen.",
    shared: {
      help: "Hilfe",
      users: "Benutzer",
      permissions: "Berechtigungen",
      systemLog: "System-Log",
      backupRestore: "Backup & Restore",
      general: "Allgemein",
      ai: "KI",
      integrations: "Integrationen",
      backup: "Backup",
      system: "System",
      loginSecurity: "Login & Sicherheit",
      mediaLibrary: "Medien-Bibliothek",
      textBlocks: "Text-Bausteine",
      brandKits: "Brand kits",
    },
  },
  account: {
    menu: "Kontomenü",
    menuHint: "Öffnet das Menü mit Profil, Sprache, Darstellung und Abmelden.",
    profile: "Profil",
    profileHint: "Öffnet das eigene Profil.",
    language: "Sprache",
    languageHint:
      "Wechselt die Sprache der Oberfläche; die Wahl bleibt auf diesem Gerät gespeichert.",
    appearance: "Darstellung",
    system: "System",
    light: "Hell",
    dark: "Dunkel",
    appearanceHint: "Stellt die Darstellung auf „{{mode}}“.",
    changePassword: "Passwort ändern",
    changePasswordHint: "Öffnet das Formular, um das eigene Passwort zu ändern.",
    changePasswordLocked:
      "Letzter aktiver Administrator — Passwort gesperrt. Lege zuerst einen zweiten Administrator an.",
    security: "Sicherheit / MFA",
    securityHint: "Zweiten Faktor und Wiederherstellungscodes verwalten.",
    logOut: "Abmelden",
    logOutHint: "Meldet ab und kehrt zur Anmeldung zurück.",
    notAvailable: "Noch nicht verfügbar",
  },
  language: {
    en: "English",
    de: "Deutsch",
    es: "Español",
  },
  search: {
    label: "Suchen",
    placeholder: "Suchen …",
    title: "Suchen",
    subtitle: "Durchsucht {{areas}}.",
    empty: "Nichts gefunden in {{areas}}.",
    loading: "Wird gesucht …",
    failed: "Die Suche ist fehlgeschlagen. Versuche es erneut.",
    results: "Suchergebnisse",
    areaSeparator: ", ",
    fieldHint: "Öffnet die Suche über alle Bereiche; Tastenkürzel {{shortcut}}.",
    inputHint: "Findet Einträge aller Bereiche nach Titel oder Inhalt.",
    hitHint: "Öffnet diesen Treffer.",
  },
  help: {
    title: "Hilfe",
    searchPlaceholder: "Hilfe durchsuchen…",
    searchHint: "Durchsucht alle Hilfeseiten nach dem eingegebenen Begriff.",
    pageHint: "Öffnet diese Hilfeseite.",
    noResults: "Keine passenden Seiten.",
    empty: "Wähle links eine Seite.",
    screenshotPending: "Screenshot folgt",
  },
  version: {
    label: "Versionsinfo",
    hint: "Zeigt Version, Commit und Build dieser Instanz.",
    title: "Version",
    version: "Version",
    noRelease: "Kein Release (Stand ohne Tag)",
    commit: "Commit",
    buildDate: "Build-Datum",
  },
  confirmDelete: {
    title: "Löschen bestätigen",
    titleOf: "{{object}} löschen?",
    cancelHint: "Schließt den Dialog, ohne etwas zu löschen.",
    cancelDisabledHint: "Schließen geht wieder, sobald das Löschen abgeschlossen ist.",
    confirmHint: "Löscht endgültig; das lässt sich nicht rückgängig machen.",
  },
  settings: {
    active: "Aktiv",
    saveHint: "Speichert die Änderungen auf dieser Seite.",
    saveDisabledHint: "Speichern geht, sobald du hier etwas geändert hast.",
    saveInvalidHint: "Speichern geht, sobald alle Angaben hier gültig sind.",
    resetHint: "Verwirft die ungespeicherten Änderungen auf dieser Seite.",
    resetDisabledHint: "Zurücksetzen geht, sobald du hier etwas geändert hast.",
  },
  timezone: {
    placeholder: "Zeitzone suchen…",
    empty: "Keine passende Zeitzone",
  },
  upload: {
    drop: "Dateien hier ablegen",
    choose: "Dateien wählen",
    rejected: "Nicht übernommen, Dateityp nicht erlaubt: {{files}}",
  },
  tags: {
    remove: "Tag {{tag}} entfernen",
    added: "Tag {{tag}} hinzugefügt",
    addedMany: "Tags {{tags}} hinzugefügt",
    removed: "Tag {{tag}} entfernt",
  },
  pager: {
    previous: "Vorheriges",
    next: "Nächstes",
  },
};
