// English is the source language of the `suite` namespace: its keys define the key set that `de`
// and `es` must match, and its wording is what they translate.
export const en = {
  actions: {
    save: "Save",
    cancel: "Cancel",
    reset: "Reset",
    restoreDefaults: "Restore defaults",
    delete: "Delete",
    create: "Create",
    back: "Back",
    close: "Close",
    replace: "Replace",
    remove: "Remove",
    testConnection: "Test connection",
    retry: "Try again",
  },
  status: {
    success: "Success",
    warning: "Warning",
    error: "Error",
    info: "Info",
    running: "Running",
    failed: "Failed",
    recovered: "Recovered",
  },
  // The text of each `StatusChip` state, in sentence case.
  state: {
    succeeded: "Succeeded",
    ok: "OK",
    connected: "Connected",
    active: "Active",
    failed: "Failed",
    error: "Error",
    untested: "Untested",
    unconfigured: "Not configured",
    expiring: "Expiring",
    running: "Running",
    inProgress: "In progress",
    set: "Set",
    notSet: "Not set",
    notTestable: "Not testable",
    unknown: "Unknown",
  },
  filter: {
    // The trigger of a filter dropdown without a choice; `allValue` is the same word as its option.
    all: "{{field}}: All",
    allValue: "All",
    placeholder: "Filter…",
    reset: "Clear filter",
    label: "Filter the list",
    hint: 'Searches every column; several words must all match. A phrase in "quotes" stays together. Single characters are ignored.',
  },
  sort: {
    label: "Sort by",
    hint: "Sets the order in which the entries appear.",
    updated: "Last edited",
  },
  pagination: {
    firstPage: "First page",
    prevPage: "Previous page",
    nextPage: "Next page",
    lastPage: "Last page",
    summary: "Page {{page}} / {{totalPages}} ({{total}})",
    pageSize: "{{size}} per page",
    pageSizeLabel: "Rows per page",
    pageSizeHint: "How many entries one page shows.",
    firstPageDisabled: "First page: possible once you are on a later page.",
    prevPageDisabled: "Previous page: possible once you are on a later page.",
    nextPageDisabled: "Next page: possible once there is a page after this one.",
    lastPageDisabled: "Last page: possible once there is a page after this one.",
  },
  list: {
    empty: "No entries yet.",
    noMatches: "No matches for this filter.",
    emptyOf: "No {{objects}} yet.",
  },
  view: {
    table: "Table",
    tiles: "Tiles",
  },
  nav: {
    label: "Primary navigation",
    toggleSidebar: "Toggle sidebar",
    home: "Opens the dashboard.",
    // Tooltip and accessible name of the `‹ <Section>` link: it names the target, not the section.
    backToDashboard: "Back to dashboard",
    // The entries several suite apps carry: one name in every app (`GL-UI-019`).
    helpHint: "Opens the help with guides to every area.",
    shared: {
      help: "Help",
      users: "Users",
      permissions: "Permissions",
      systemLog: "System log",
      backupRestore: "Backup & restore",
      general: "General",
      ai: "AI",
      integrations: "Integrations",
      backup: "Backup",
      system: "System",
      loginSecurity: "Login & security",
      mediaLibrary: "Media library",
      textBlocks: "Text blocks",
      brandKits: "Brand kits",
    },
  },
  account: {
    menu: "Account menu",
    menuHint: "Opens the menu with profile, language, appearance and sign-out.",
    profile: "Profile",
    profileHint: "Opens your own profile.",
    language: "Language",
    languageHint: "Switches the interface language; your choice is remembered on this device.",
    appearance: "Appearance",
    system: "System",
    light: "Light",
    dark: "Dark",
    appearanceHint: "Sets the appearance to “{{mode}}”.",
    changePassword: "Change password",
    changePasswordHint: "Opens the form to change your own password.",
    changePasswordLocked: "Last active admin — password locked. Create a second admin first.",
    security: "Security / MFA",
    securityHint: "Manage the second factor and recovery codes.",
    logOut: "Log out",
    logOutHint: "Signs out and returns to the sign-in page.",
    notAvailable: "Not available yet",
  },
  // Each language under its own name, the same in every interface language.
  language: {
    en: "English",
    de: "Deutsch",
    es: "Español",
  },
  search: {
    label: "Search",
    placeholder: "Search …",
    title: "Search",
    subtitle: "Searches {{areas}}.",
    empty: "Nothing found in {{areas}}.",
    loading: "Searching …",
    failed: "The search failed. Try again.",
    results: "Search results",
    areaSeparator: ", ",
    fieldHint: "Opens the search across all areas; shortcut {{shortcut}}.",
    inputHint: "Finds entries of every area by title or content.",
    hitHint: "Opens this result.",
  },
  help: {
    title: "Help",
    searchPlaceholder: "Search help…",
    searchHint: "Searches every help page for the term you enter.",
    pageHint: "Opens this help page.",
    noResults: "No matching pages.",
    empty: "Pick a page on the left.",
    screenshotPending: "Screenshot pending",
  },
  version: {
    label: "Version info",
    hint: "Shows the version, commit and build of this instance.",
    title: "Version",
    version: "Version",
    noRelease: "No release (untagged build)",
    commit: "Commit",
    buildDate: "Build date",
  },
  confirmDelete: {
    title: "Confirm deletion",
    cancelHint: "Closes the dialog without deleting anything.",
    cancelDisabledHint: "Closing becomes possible again once the deletion has finished.",
    confirmHint: "Deletes for good; this cannot be undone.",
  },
  settings: {
    active: "Active",
    saveHint: "Saves the changes on this page.",
    saveDisabledHint: "Saving becomes possible once you have changed something here.",
    saveInvalidHint: "Saving becomes possible once every entry here is valid.",
    resetHint: "Discards the unsaved changes on this page.",
    resetDisabledHint: "Resetting becomes possible once you have changed something here.",
  },
  timezone: {
    placeholder: "Search time zone…",
    empty: "No matching time zone",
  },
} as const;

type Widen<T> = { [K in keyof T]: T[K] extends string ? string : Widen<T[K]> };

export type SuiteStrings = Widen<typeof en>;
