import type { SuiteStrings } from "./en.js";

export const es: SuiteStrings = {
  actions: {
    save: "Guardar",
    cancel: "Cancelar",
    reset: "Restablecer",
    restoreDefaults: "Restaurar valores predeterminados",
    delete: "Eliminar",
    create: "Crear",
    back: "Volver",
    close: "Cerrar",
    replace: "Reemplazar",
    remove: "Quitar",
    testConnection: "Probar conexión",
  },
  status: {
    success: "Éxito",
    warning: "Advertencia",
    error: "Error",
    info: "Información",
    running: "En curso",
    failed: "Fallido",
    recovered: "Recuperado",
  },
  state: {
    succeeded: "Correcto",
    ok: "OK",
    connected: "Conectado",
    active: "Activo",
    failed: "Fallido",
    error: "Error",
    untested: "Sin probar",
    unconfigured: "Sin configurar",
    expiring: "Por caducar",
    running: "En ejecución",
    inProgress: "En curso",
    set: "Definido",
    notSet: "No definido",
    notTestable: "No comprobable",
    unknown: "Desconocido",
  },
  filter: {
    all: "{{field}}: Todos",
    allValue: "Todos",
    placeholder: "Filtrar…",
    reset: "Borrar filtro",
    label: "Filtrar la lista",
    hint: 'Busca en todas las columnas; varias palabras deben coincidir todas. Una frase entre "comillas" se mantiene unida. Los caracteres sueltos se ignoran.',
  },
  sort: {
    label: "Ordenar por",
    hint: "Define en qué orden aparecen las entradas.",
    updated: "Última edición",
  },
  pagination: {
    firstPage: "Primera página",
    prevPage: "Página anterior",
    nextPage: "Página siguiente",
    lastPage: "Última página",
    summary: "Página {{page}} / {{totalPages}} ({{total}})",
    pageSize: "{{size}} por página",
    pageSizeLabel: "Filas por página",
    pageSizeHint: "Cuántas entradas muestra una página.",
    firstPageDisabled: "Primera página: posible en cuanto estés en una página posterior.",
    prevPageDisabled: "Página anterior: posible en cuanto estés en una página posterior.",
    nextPageDisabled: "Página siguiente: posible en cuanto haya una página después de esta.",
    lastPageDisabled: "Última página: posible en cuanto haya una página después de esta.",
  },
  list: {
    empty: "Aún no hay entradas.",
    noMatches: "No se encontraron entradas.",
  },
  nav: {
    label: "Navegación principal",
    toggleSidebar: "Mostrar u ocultar la barra lateral",
    home: "Abre el panel.",
    backToDashboard: "Volver al panel",
    helpHint: "Abre la ayuda con guías de todas las áreas.",
    shared: {
      help: "Ayuda",
      users: "Usuarios",
      permissions: "Permisos",
      systemLog: "Registro del sistema",
      backupRestore: "Copia y restauración",
      general: "General",
      ai: "IA",
      integrations: "Integraciones",
      backup: "Copia",
      system: "Sistema",
      loginSecurity: "Acceso y seguridad",
      mediaLibrary: "Biblioteca de medios",
      textBlocks: "Bloques de texto",
      brandKits: "Kits de marca",
    },
  },
  account: {
    menu: "Menú de la cuenta",
    menuHint: "Abre el menú con perfil, idioma, apariencia y cierre de sesión.",
    profile: "Perfil",
    profileHint: "Abre el perfil propio.",
    language: "Idioma",
    languageHint: "Cambia el idioma de la interfaz; la elección se guarda en este dispositivo.",
    appearance: "Apariencia",
    system: "Sistema",
    light: "Claro",
    dark: "Oscuro",
    appearanceHint: "Cambia la apariencia a «{{mode}}».",
    changePassword: "Cambiar contraseña",
    changePasswordHint: "Abre el formulario para cambiar la contraseña propia.",
    changePasswordLocked:
      "Último administrador activo — contraseña bloqueada. Crea primero un segundo administrador.",
    security: "Seguridad / MFA",
    securityHint: "Gestionar el segundo factor y los códigos de recuperación.",
    logOut: "Cerrar sesión",
    logOutHint: "Cierra la sesión y vuelve al inicio de sesión.",
    notAvailable: "Aún no disponible",
  },
  language: {
    en: "English",
    de: "Deutsch",
    es: "Español",
  },
  search: {
    label: "Buscar",
    placeholder: "Buscar …",
    title: "Buscar",
    subtitle: "Busca en {{areas}}.",
    empty: "No se encontró nada en {{areas}}.",
    loading: "Buscando …",
    failed: "La búsqueda falló. Inténtalo de nuevo.",
    results: "Resultados de búsqueda",
    areaSeparator: ", ",
    fieldHint: "Abre la búsqueda en todas las áreas; atajo {{shortcut}}.",
    inputHint: "Encuentra entradas de todas las áreas por título o contenido.",
    hitHint: "Abre este resultado.",
  },
  help: {
    title: "Ayuda",
    searchPlaceholder: "Buscar en la ayuda…",
    searchHint: "Busca el término introducido en todas las páginas de ayuda.",
    pageHint: "Abre esta página de ayuda.",
    noResults: "No hay páginas coincidentes.",
    empty: "Elige una página a la izquierda.",
    screenshotPending: "Captura pendiente",
  },
  version: {
    label: "Información de versión",
    hint: "Muestra la versión, el commit y la compilación de esta instancia.",
    title: "Versión",
    version: "Versión",
    noRelease: "Sin versión publicada (compilación sin etiqueta)",
    commit: "Commit",
    buildDate: "Fecha de compilación",
  },
  confirmDelete: {
    title: "Confirmar eliminación",
    cancelHint: "Cierra el diálogo sin borrar nada.",
    cancelDisabledHint: "Cerrar vuelve a ser posible en cuanto termine la eliminación.",
    confirmHint: "Borra definitivamente; no se puede deshacer.",
  },
  settings: {
    active: "Activo",
    saveHint: "Guarda los cambios de esta página.",
    saveDisabledHint: "Se puede guardar en cuanto cambies algo aquí.",
    saveInvalidHint: "Se puede guardar en cuanto todos los datos de aquí sean válidos.",
    resetHint: "Descarta los cambios sin guardar de esta página.",
    resetDisabledHint: "Se puede restablecer en cuanto cambies algo aquí.",
  },
  timezone: {
    placeholder: "Buscar zona horaria…",
    empty: "Ninguna zona horaria coincide",
  },
};
